const constants = {
  ADD_RESERVATION: 'ADD_RESERVATION',
  SET_RESERVATIONS: 'SET_RESERVATIONS',
  SET_RESERVATION: 'SET_RESERVATION',
  SET_FETCHING: 'SET_FETCHING',
  CANCEL_FETCHING: 'CANCEL_FETCHING'
};

export default constants
